# Generated by Django 5.0.6 on 2024-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stilo_Rico', '0005_alter_cart_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
